//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mediawiki.org/xml/export-0.10/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.mediawiki.org/xml/export-0.10/", IsNullable=false)]
public partial class mediawiki {
    
    private mediawikiSiteinfo[] siteinfoField;
    
    private mediawikiPage[] pageField;
    
    private string versionField;
    
    private string langField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("siteinfo")]
    public mediawikiSiteinfo[] siteinfo {
        get {
            return this.siteinfoField;
        }
        set {
            this.siteinfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("page")]
    public mediawikiPage[] page {
        get {
            return this.pageField;
        }
        set {
            this.pageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mediawiki.org/xml/export-0.10/")]
public partial class mediawikiSiteinfo {
    
    private string sitenameField;
    
    private string dbnameField;
    
    private string baseField;
    
    private string generatorField;
    
    private string caseField;
    
    private mediawikiSiteinfoNamespacesNamespace[][] namespacesField;
    
    /// <remarks/>
    public string sitename {
        get {
            return this.sitenameField;
        }
        set {
            this.sitenameField = value;
        }
    }
    
    /// <remarks/>
    public string dbname {
        get {
            return this.dbnameField;
        }
        set {
            this.dbnameField = value;
        }
    }
    
    /// <remarks/>
    public string @base {
        get {
            return this.baseField;
        }
        set {
            this.baseField = value;
        }
    }
    
    /// <remarks/>
    public string generator {
        get {
            return this.generatorField;
        }
        set {
            this.generatorField = value;
        }
    }
    
    /// <remarks/>
    public string @case {
        get {
            return this.caseField;
        }
        set {
            this.caseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("namespace", typeof(mediawikiSiteinfoNamespacesNamespace[]))]
    public mediawikiSiteinfoNamespacesNamespace[][] namespaces {
        get {
            return this.namespacesField;
        }
        set {
            this.namespacesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mediawiki.org/xml/export-0.10/")]
public partial class mediawikiSiteinfoNamespacesNamespace {
    
    private string keyField;
    
    private string caseField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @case {
        get {
            return this.caseField;
        }
        set {
            this.caseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mediawiki.org/xml/export-0.10/")]
public partial class mediawikiPage {
    
    private string titleField;
    
    private string nsField;
    
    private string idField;
    
    private mediawikiPageRevision[] revisionField;
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string ns {
        get {
            return this.nsField;
        }
        set {
            this.nsField = value;
        }
    }
    
    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("revision")]
    public mediawikiPageRevision[] revision {
        get {
            return this.revisionField;
        }
        set {
            this.revisionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mediawiki.org/xml/export-0.10/")]
public partial class mediawikiPageRevision {
    
    private string idField;
    
    private string parentidField;
    
    private string timestampField;
    
    private string minorField;
    
    private string commentField;
    
    private string modelField;
    
    private string formatField;
    
    private string sha1Field;
    
    private mediawikiPageRevisionContributor[] contributorField;
    
    private mediawikiPageRevisionText[] textField;
    
    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string parentid {
        get {
            return this.parentidField;
        }
        set {
            this.parentidField = value;
        }
    }
    
    /// <remarks/>
    public string timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    public string minor {
        get {
            return this.minorField;
        }
        set {
            this.minorField = value;
        }
    }
    
    /// <remarks/>
    public string comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    public string model {
        get {
            return this.modelField;
        }
        set {
            this.modelField = value;
        }
    }
    
    /// <remarks/>
    public string format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    public string sha1 {
        get {
            return this.sha1Field;
        }
        set {
            this.sha1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contributor")]
    public mediawikiPageRevisionContributor[] contributor {
        get {
            return this.contributorField;
        }
        set {
            this.contributorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("text", IsNullable=true)]
    public mediawikiPageRevisionText[] text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mediawiki.org/xml/export-0.10/")]
public partial class mediawikiPageRevisionContributor {
    
    private string ipField;
    
    private string usernameField;
    
    private string idField;
    
    /// <remarks/>
    public string ip {
        get {
            return this.ipField;
        }
        set {
            this.ipField = value;
        }
    }
    
    /// <remarks/>
    public string username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mediawiki.org/xml/export-0.10/")]
public partial class mediawikiPageRevisionText {
    
    private string bytesField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bytes {
        get {
            return this.bytesField;
        }
        set {
            this.bytesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mediawiki.org/xml/export-0.10/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.mediawiki.org/xml/export-0.10/", IsNullable=false)]
public partial class NewDataSet {
    
    private mediawiki[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mediawiki")]
    public mediawiki[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
